# Generated by Django 3.1.7 on 2021-07-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20210521_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
